{% set name = "qcengine" %}
{% set version = "0.20.1" %}
{% set sha256 = "859c44edbd1b3b1fc1f0acf8720042ef0576dce8a4471c2b759e1443c1bfca18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.23.0

test:
  imports:
    - qcengine
  requires:
    - pytest
  commands:
    - pytest --pyargs qcengine

about:
  home: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

  doc_url: https://qcengine.readthedocs.io/en/latest/
  dev_url: http://github.com/MolSSI/QCEngine

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
