{% set name = "qcengine" %}
{% set version = "__BUILD_VERSION__" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # This path is made possible by hacking .scripts/run_docker_build.sh
  # This REQUIRES that the parent directory containing this repo has a QCEngine directory containing the QCE repo
  # This is kindof hack, but Conda's build system is weird
  - path: ./qce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - pydantic >=1.8.2
    - pyyaml
    - py-cpuinfo
    - psutil
    - qcelemental >=0.26.0,<0.30.0

about:
  home: http://github.com/MolSSI/QCEngine
  doc_url: https://molssi.github.io/QCEngine/
  dev_url: http://github.com/MolSSI/QCEngine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper for Quantum Chemistry engines that adheres to the MolSSI (molssi.org) QCSchema.

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
    - bennybp
    - loriab
