{% set name = "libint" %}
{% set version = "__BUILD_VERSION__" %}

# source tarball pattern for upstream
# {% set url = "https://github.com/evaleev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tgz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ./libint

build:
  number: 0
  binary_relocation: true
  run_exports:
    - {{ pin_subpackage('libint', max_pin='x') }}
  ignore_run_exports_from:
  # The next statement breaks the fortran compiler on arm64.
  # Remove periodically to check, if this resolved itself.
    - {{ compiler('fortran') }}  # [linux or (osx and not arm64)]
  script_env:
    - ENABLE_FORTRAN=ON  # [linux or (osx and not arm64)]
    - ENABLE_FORTRAN=OFF  # [osx and arm64]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [linux or (osx and not arm64)]
    - cmake
    - ninja
  host:
    # note: alternately, could withhold boost here so that a vendored subset of boost headers gets installed
    #   at include/libint2/boost/ . Then downstream builds against libint2 don't need a Boost dependency.
    - libboost-headers
    - eigen
    - openmp  # [linux or (osx and not arm64)]

about:
  home: https://github.com/evaleev/libint
  dev_url: https://github.com/evaleev/libint
  doc_url: https://github.com/evaleev/libint/wiki
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - LICENSE
    - COPYING.LESSER
  license_family: LGPL
  summary: "Libint is E. Valeev's library for the evaluation of molecular integrals of many-body operators over Gaussian functions"

extra:
  recipe-maintainers:
    - felipeZ
    - loriab
