travis:
  secure:
    BINSTAR_TOKEN: I+uiKj/5wO76eUQmjoPERzXG+N5iNfarii89aDbghLfet5iR6eg8XOKd+CT4yjRbyGuOmKU57J4Xxrmo+O2vUW7r7GiRsjLquPOOlE6nB/OtEesVtOwJomtNMqPMaiAUs9Qpwy/cWzrHtj9MLyiDCCF0fVK8JO5YgVGUU++fE/xbQJdsXPo8fLDzRpgI4dP6AB0GP+gnCG4gVLsct3WUCaWj6NsSR6QVD0JnPVXbI1F6X6Iimg2VxT45W01fdPpFWVybfKqSdg+wyxNYg3wl1vHQkMvSIfn/s4cY77NVWjUfkBybeoTjw9e3ektWQAD9WavjMlCyMZ0OcO1RARlNoy98TB7Ym9Ib++bDlKl8PfPGXlK3twnlSSvW+K9nTnkTQnlY3BUX8htOqIpi9rRRlaTgg9DcwzjGX1qkgj4z2r0YXJj8+tOE3U52OA1WC2yNaN+sIrIdPUJW4pVhuKe7HkzjJt/AS4yLLn6oNz9nprgJyoYloLylkxTG1DBz/osd4efLCmqPjmK4BJa/htttSKCfciPFhstWWEY36JSpWQPb9pJAYT+YxM3+5xKCy6ZOxBbKFA9o6ZeEZqJrqqw+uqKpq20gLuQbiT96ywTvHuWF99PQMC6ea6K+CrZkQV/aPSter4iI4lpPTZnY5m6T1Btdjt0Pnp4ZuZfpT/Z7Fqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
